# # ----------------- Copied from particle template -----------------
# Site settings
title: "Niu Liu (刘牛)"
hometitle: "Welcome to homepage of Niu Liu (刘牛)"
description: "My personal website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liuniu.fun" 

# User settings
username: "Niu Liu"
user_description: |
  TBD
user_title: "Assistant Professor in Astronomy"
avatar: "bio.png"

# Google-analytics
google-analytics:
  id: "G-KKSL7XM2F6"

exclude: ['package.json', 'src' , 'node_modules']

# ----------------- Copied from academicpages template -----------------
# Site Author
author:
  name             : "Niu Liu"
  avatar           : "bio-photo.png"
  location         : "Nanjing, China"
  city             : "Nanjing"
  employer         : "Nanjing University"
  employer_url     : "https://astronomy.nju.edu.cn/EN/index.html"
  email            : "secret"
  researchgate     : "https://www.researchgate.net/profile/Niu-Liu?ev=hdr_xprf"
  orcid            : "0000-0003-2778-002X"
  adslib           : "https://ui.adsabs.harvard.edu/user/libraries/EWTz-0tVSn6LqIz7ZgLMgg"
# locale                   : "en-US"
encoding: "utf-8"
title_separator          : "-"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
future                   : true
atom_feed:
  path                   : # blank (default) uses feed.xml

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
    
# Main Navigation
main_navigation:
  - title: "CV"
    url: /cv/

  - title: "Publications"
    url: /publications/

  - title: "Projects"
    url: /projects/

  - title: "Talks"
    url: /talks/

  - title: "Teaching"
    url: /teaching/

#  - title: "Portfolio"
#   url: /portfolio/

  - title: "Blog"
    url: /blogs/

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
#   portfolio:
#     output: true
#     permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       read_time: true
#       comments: true
#       share: true
#       related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
#   # _portfolio
#   - scope:
#       path: ""
#       type: portfolio
#     values:
#       layout: single
#       author_profile: true
#       share: true
#       comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# ----------------- Copied from lemonchann template -----------------
blogdescription: "Knowledge is for sharing."
blogname: "Neo's blog"

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://raw.githubusercontent.com/Niu-Liu/Niu-Liu.github.io/master/assets/img/Headshot.ico

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
blog-navigation:
# - name: 首页
  - name: Home
    url: /
# - name: 博客
  - name: Blog
    url: /blogs
# - name: 归档
  - name: Archive
    url: /archive
# - name: 标签
  - name: Tags
    url: /tags

# Pagination
paginate: 8
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Text under the icons in footer
footer-text:
permalink: /:title/
paginate_path: /blogs/page:num/
 
theme: jekyll-theme-minimal

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
  
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
  
words_per_minute: 160
excerpt_separator: "<!-- more -->"
incremental: false
  
# Markdown Processing
kramdown:
    input: GFM
    hard_wrap: false
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    enable_coderay: false
    syntax_highlighter: rouge
    syntax_highlighter_opts:
      # Use existing pygments syntax highlighting css
      css_class: 'highlight'

# # Reading Files
# include:
#   - .htaccess
#   - _pages
#   - files
# exclude:
#   - "*.sublime-project"
#   - "*.sublime-workspace"
#   - .asset-cache
#   - .bundle
#   - .jekyll-assets-cache
#   - .sass-cache
#   - CHANGELOG
#   - Capfile
#   - Gemfile
#   - Gruntfile.js
#   - LICENSE
#   - README
#   - Rakefile
#   - assets/js/_main.js
#   - assets/js/plugins
#   - assets/js/vendor
#   - config
#   - gulpfile.js
#   - log
#   - node_modules
#   - package.json
#   - tmp
#   - vendor
# keep_files:
#   - .git
#   - .svn
#
#


# # # ----------------- Copied from academic -----------------
# 
# # Sass/SCSS
# sass:
#   sass_dir: _sass
#   style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
# 
# 
# 
# include:
#   - .htaccess
#   - _pages
#   - files
# exclude:
#   - "*.sublime-project"
#   - "*.sublime-workspace"
#   - .asset-cache
#   - .bundle
#   - .jekyll-assets-cache
#   - .sass-cache
#   - CHANGELOG
#   - Capfile
#   - Gemfile
#   - Gruntfile.js
#   - LICENSE
#   - README
#   - Rakefile
#   - assets/js/_main.js
#   - assets/js/plugins
#   - assets/js/vendor
#   - config
#   - gulpfile.js
#   - log
#   - node_modules
#   - package.json
#   - tmp
#   - vendor
#   - yarn.lock
#   - CNAME
# keep_files:
#   - .git
#   - .svn
# encoding: "utf-8"
