# Site settings
title: "Niu Liu (刘牛)"
hometitle: "Welcome to homepage of Niu Liu (刘牛)"
description: "My personal website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liuniu.fun" 
blogdescription: "Knowledge is for sharing."
blogname: "Neo's blog"

# User settings
username: "Niu Liu"
user_description: |
  I obtained my BSc in 2015 and my PhD degree in 2020,
  both at Nanjing University (NJU). I was a joint PhD student in SYRTE,
  Paris Observatory from November 2017 to October 2018.
  Since September 2020, I was sponsored by the Yu-Xiu Young Scholar Program at 
  NJU and started my postdoc research there.
  Now I got a tenure-track position and became an assistant professor at NJU in 2023.
user_title: "PhD in Astronomy"
avatar: "bio.png"

# # ----------------- Copied from academic -----------------
# Google-analytics
google-analytics   : "G-KKSL7XM2F6"

# Site Author
author:
  name             : "Niu Liu"
  avatar           : "bio-photo.png"
  location         : "Nanjing, China"
  city             : "Nanjing"
  employer         : "Nanjing University"
  employer_url     : "https://astronomy.nju.edu.cn/EN/index.html"
  email            : "secret"
  researchgate     : "https://www.researchgate.net/profile/Niu-Liu?ev=hdr_xprf"
  orcid            : "0000-0003-2778-002X"
  adslib           : "https://ui.adsabs.harvard.edu/user/libraries/EWTz-0tVSn6LqIz7ZgLMgg"

# main links 
main_navigation:
  - title: "CV"
    url: /cv/

  - title: "Publications"
    url: /publications/

  - title: "Projects"
    url: /projects/

  - title: "Talks"
    url: /talks/

  - title: "Teaching"
    url: /teaching/

#  - title: "Portfolio"
#   url: /portfolio/

  - title: "Blog"
    url: /blogs/

#  - title: "Guide"
#    url: /markdown/


markdown_ext: "markdown,mkdown,mkdn,mkd,md"
  
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
  
excerpt_separator: "<!-- more -->"
incremental: false
  
# Markdown Processing
kramdown:
    input: GFM
    hard_wrap: false
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    enable_coderay: false
    syntax_highlighter: rouge
    syntax_highlighter_opts:
      # Use existing pygments syntax highlighting css
      css_class: 'highlight'

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# ----------------- Copied from lemonchann -----------------
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://raw.githubusercontent.com/Niu-Liu/Niu-Liu.github.io/master/assets/img/Headshot.ico

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
# - name: 首页
  - name: Home
    url: /
# - name: 博客
  - name: Blog
    url: /blogs
# - name: 归档
  - name: Archive
    url: /archive
# - name: 标签
  - name: Tags
    url: /tags

# Pagination
paginate: 8
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Text under the icons in footer
footer-text:
#  
#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /blogs/page:num/
 
theme: jekyll-theme-minimal

include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
  - yarn.lock
  - CNAME
keep_files:
  - .git
  - .svn
encoding: "utf-8"
